In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/00-raw/population_cmap_2022.csv")

In [3]:
df

,OBJECTID,GEOID,GEOG,2000_POP,2010_POP,2020_POP,2020_HH,2020_HH_SIZE,TOT_POP,UND5,...,highly_walkable_pop_pct,highly_walkable_emp_pct,assoc_plus_pct,in_lbr_frc_pct,pct_pop_access_4_acres_per_1k,pct_pop_access_10_acres_per_1k,impervious_acres_per_hh,modhigh_ta_pop_pct,modhigh_ta_emp_pct,nonsov_pct
0,1,14,Albany Park,57655,51542,48396,17161,2.742731,49280.00000,2835.000000,...,1.000000,1.000000,0.457503,0.819020,0.000000,0.000000,0.052479,1.0,1.0,0.538134
1,2,57,Archer Heights,12644,13393,14196,4163,3.403315,13533.00000,907.000000,...,0.994887,0.439369,0.146899,0.791877,0.000000,0.000000,0.259476,1.0,1.0,0.407037
2,3,34,Armour Square,12032,13391,13890,5648,2.446353,13438.84426,696.557377,...,1.000000,1.000000,0.323964,0.815347,0.200206,0.000000,0.094773,1.0,1.0,0.569835
3,4,70,Ashburn,39584,41081,41098,12909,3.140367,42902.00000,2641.000000,...,0.872049,0.587267,0.297459,0.776386,0.144637,0.000000,0.160631,1.0,1.0,0.291486
4,5,71,Auburn Gresham,55928,48743,44878,18071,2.476620,46698.00000,2959.000000,...,0.950208,0.878471,0.245749,0.708108,0.027726,0.000000,0.091181,1.0,1.0,0.406434
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,73,65,West Lawn,29235,33355,33662,9244,3.635115,32162.00000,2518.000000,...,0.927448,0.454832,0.172299,0.789833,0.026699,0.000000,0.154499,1.0,1.0,0.293069
73,74,53,West Pullman,36649,29651,26104,9650,2.703316,26484.00000,1739.000000,...,0.909574,0.874166,0.250147,0.783332,0.182974,0.000000,0.138739,1.0,1.0,0.334058
74,75,2,West Ridge,73199,71942,77122,26493,2.850980,78763.00000,6570.000000,...,1.000000,1.000000,0.469918,0.774887,0.193019,0.000000,0.054500,1.0,1.0,0.366949
75,76,24,West Town,87435,82236,87781,42920,2.033527,84437.00000,4964.000000,...,1.000000,1.000000,0.758246,0.902659,0.095257,0.000000,0.054430,1.0,1.0,0.578903
76,77,42,Woodlawn,27086,23740,24425,10517,2.186270,22502.00000,1416.000000,...,0.999056,0.792316,0.361082,0.732015,0.902429,0.240525,0.072712,1.0,1.0,0.569234

In [4]:
# df.dtypes
for column in df.columns:
    print(f"{column}: {df[column].dtype}")

OBJECTID: int64
GEOID: int64
GEOG: object
2000_POP: int64
2010_POP: int64
2020_POP: int64
2020_HH: int64
2020_HH_SIZE: float64
TOT_POP: float64
UND5: float64
A5_19: float64
A20_34: float64
A35_49: float64
A50_64: float64
A65_74: float64
A75_84: float64
OV85: float64
MED_AGE: float64
WHITE: float64
HISP: float64
BLACK: float64
ASIAN: float64
OTHER: float64
POP_HH: float64
POP_16OV: float64
IN_LBFRC: float64
EMP: float64
UNEMP: float64
NOT_IN_LBFRC: float64
TOT_WRKR16OV: float64
WORK_AT_HOME: float64
TOT_COMM: float64
DROVE_AL: float64
CARPOOL: float64
TRANSIT: float64
WALK_BIKE: float64
COMM_OTHER: float64
AGG_TT: float64
NO_VEH: float64
ONE_VEH: float64
TWO_VEH: float64
THREEOM_VEH: float64
POP_25OV: float64
LT_HS: float64
HS: float64
SOME_COLL: float64
ASSOC: float64
BACH: float64
GRAD_PROF: float64
INC_LT_25K: float64
INC_25_50K: float64
INC_50_75K: float64
INC_75_100K: float64
INC_100_150K: float64
INC_GT_150: float64
MEDINC: float64
INCPERCAP: float64
TOT_HH: float64
OWN_OCC_HU: float64
RENT_OCC_HU: float64
VAC_HU: float64
HU_TOT: float64
HU_SNG_DET: float64
HU_SNG_ATT: float64
HU_2UN: float64
HU_3_4UN: float64
HU_5_9UN: float64
HU_10_19UN: float64
HU_GT_19UN: float64
HU_MOBILE: float64
MED_ROOMS: float64
HA_AFT2000: float64
HA_70_00: float64
HA_40_70: float64
HA_BEF1940: float64
MED_HA: float64
BR_0_1: float64
BR_2: float64
BR_3: float64
BR_4: float64
BR_5: float64
HV_LT_150K: float64
HV_150_300K: float64
HV_300_500K: float64
HV_GT_500K: float64
MED_HV: float64
CASHRENT_HH: float64
RENT_LT500: float64
RENT_500_999: float64
RENT_1000_1499: float64
RENT_1500_2499: float64
RENT_GT2500: float64
MED_RENT: float64
COMPUTER: float64
ONLY_SMARTPHONE: float64
NO_COMPUTER: float64
INTERNET: float64
BROADBAND: float64
NO_INTERNET: float64
TOT_EMP_RES: int64
RES_NAICS1_TYPE: object
RES_NAICS2_TYPE: object
RES_NAICS3_TYPE: object
RES_NAICS4_TYPE: object
RES_NAICS5_TYPE: object
RES_NAICS1_COUNT: int64
RES_NAICS2_COUNT: int64
RES_NAICS3_COUNT: int64
RES_NAICS4_COUNT: int64
RES_NAICS5_COUNT: int64
TOT_EMP_WORK: int64
WORK_NAICS1_TYPE: object
WORK_NAICS2_TYPE: object
WORK_NAICS3_TYPE: object
WORK_NAICS4_TYPE: object
WORK_NAICS5_TYPE: object
WORK_NAICS1_COUNT: int64
WORK_NAICS2_COUNT: int64
WORK_NAICS3_COUNT: int64
WORK_NAICS4_COUNT: int64
WORK_NAICS5_COUNT: int64
RES_CITY1_TYPE: object
RES_CITY2_TYPE: object
RES_CITY3_TYPE: object
RES_CITY4_TYPE: object
RES_CITY5_TYPE: object
RES_CITY1_COUNT: int64
RES_CITY2_COUNT: int64
RES_CITY3_COUNT: int64
RES_CITY4_COUNT: int64
RES_CITY5_COUNT: int64
WORK_CITY1_TYPE: object
WORK_CITY2_TYPE: object
WORK_CITY3_TYPE: object
WORK_CITY4_TYPE: object
WORK_CITY5_TYPE: object
WORK_CITY1_COUNT: int64
WORK_CITY2_COUNT: int64
WORK_CITY3_COUNT: int64
WORK_CITY4_COUNT: int64
WORK_CITY5_COUNT: int64
IDES_START_EMP: float64
IDES_MID_EMP: float64
IDES_CURR_EMP: float64
AVG_VMT: float64
RET_SALES: float64
GEN_MERCH: float64
RES_EAV: float64
CMRCL_EAV: float64
IND_EAV: float64
RAIL_EAV: float64
FARM_EAV: float64
MIN_EAV: float64
TOT_EAV: float64
TRANSIT_LOW_PCT: float64
TRANSIT_MOD_PCT: float64
TRANSIT_HIGH_PCT: float64
WALKABLE_LOW_PCT: float64
WALKABLE_MOD_PCT: float64
WALKABLE_HIGH_PCT: float64
OPEN_SPACE_PER_1000: float64
TOT_ACRES: float64
SF: float64
Sfperc: float64
MF: float64
Mfperc: float64
MIX: float64
MIXperc: float64
COMM: float64
COMMperc: float64
INST: float64
INSTperc: float64
IND: float64
INDperc: float64
TRANS: float64
TRANSperc: float64
AG: float64
Agperc: float64
OPEN: float64
OPENperc: float64
VACANT: float64
VACperc: float64
CT_1PHH: float64
CT_2PHH: float64
CT_3PHH: float64
CT_4MPHH: float64
CT_FAM_HH: float64
CT_SP_WCHILD: float64
CT_NONFAM_HH: float64
HCUND20K: float64
HCUND20K_LT20PCT: float64
HCUND20K_20_29PCT: float64
HCUND20K_30MPCT: float64
HC20Kto49K: float64
HC20Kto49K_LT20PCT: float64
HC20Kto49K_20_29PCT: float64
HC20Kto49K_30MPCT: float64
HC50Kto75K: float64
HC50Kto75K_LT20PCT: float64
HC50Kto75K_20_29PCT: float64
HC50Kto75K_30MPCT: float64
HCOV75K: float64
HCOV75K_LT20PCT: float64
HCOV75K_20_29PCT: float64
HCOV75K_30MPCT: float64
NATIVE: float64
FOR_BORN: float64
POP_OV5: float64
NOT_ENGLISH: float64
LING_ISO: float64
ENGLISH: float64
SPANISH: float64
SLAVIC: float64
CHINESE: float64
TAGALOG: float64
ARABIC: float64
KOREAN: float64
OTHER_ASIAN: float64
OTHER_EURO: float64
OTHER_UNSPEC: float64
2000_WHITE: int64
2000_HISP: int64
2000_BLACK: int64
2000_ASIAN: int64
2000_OTHER: int64
2000_UND19: float64
2000_A20_34: float64
2000_A35_49: float64
2000_A50_64: float64
2000_OV65: float64
2000_MED_AGE: float64
2000_TOT_HH: float64
2000_OWN_OCC_HU: float64
2000_RENT_OCC_HU: float64
2000_VAC_HU: float64
2000_HU_TOT: float64
2000_LT_HS: float64
2000_HS: float64
2000_SOME_COLL: float64
2000_ASSOC: float64
2000_BACH: float64
2000_GRAD_PROF: float64
2000_POP_25OV: float64
HT_Cost_Typical: float64
HT_Cost_Mod: float64
H_Cost_Typical: float64
H_Cost_Mod: float64
T_Cost_Typical: float64
T_Cost_Mod: float64
highly_walkable_pop_pct: float64
highly_walkable_emp_pct: float64
assoc_plus_pct: float64
in_lbr_frc_pct: float64
pct_pop_access_4_acres_per_1k: float64
pct_pop_access_10_acres_per_1k: float64
impervious_acres_per_hh: float64
modhigh_ta_pop_pct: float64
modhigh_ta_emp_pct: float64
nonsov_pct: float64

### keep only worthwhile fields

In [5]:
df_census = df[['GEOG','2020_POP','VAC_HU','HU_TOT','VACANT','VACperc']]
df_census['community_caps']=df_census['GEOG'].str.upper()
df_census.columns = df_census.columns.str.lower()
df_census = df_census.rename(columns={'geog':'community_name'})
df_census

/tmp/ipykernel_2853/2209310869.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_census['community_caps']=df_census['GEOG'].str.upper()

,community_name,2020_pop,vac_hu,hu_tot,vacant,vacperc,community_caps
0,Albany Park,48396,1448.000000,18230.000000,5.322983,0.004331,ALBANY PARK
1,Archer Heights,14196,406.000000,4538.000000,29.231599,0.022770,ARCHER HEIGHTS
2,Armour Square,13890,393.513552,5860.348806,15.696404,0.024625,ARMOUR SQUARE
3,Ashburn,41098,540.000000,13479.000000,59.468213,0.019123,ASHBURN
4,Auburn Gresham,44878,3364.000000,20617.000000,119.122147,0.049388,AUBURN GRESHAM
...,...,...,...,...,...,...,...
72,West Lawn,33662,525.000000,9701.000000,46.394184,0.024551,WEST LAWN
73,West Pullman,26104,2147.000000,11210.000000,221.071452,0.096914,WEST PULLMAN
74,West Ridge,77122,2185.000000,28054.000000,11.765845,0.005207,WEST RIDGE
75,West Town,87781,3177.000000,41891.000000,62.407906,0.021311,WEST TOWN
76,Woodlawn,24425,2436.000000,11960.000000,122.772101,0.092636,WOODLAWN

### Replace 'The Loop' with 'Loop', to match community names in other data sets

In [6]:
# boundaries shapefile refers to downtown as "LOOP", not "The Loop"
df_census['community_name']= df_census['community_name'].replace('The Loop','Loop')
df_census['community_caps']= df_census['community_caps'].replace('THE LOOP','LOOP')
df_census

,community_name,2020_pop,vac_hu,hu_tot,vacant,vacperc,community_caps
0,Albany Park,48396,1448.000000,18230.000000,5.322983,0.004331,ALBANY PARK
1,Archer Heights,14196,406.000000,4538.000000,29.231599,0.022770,ARCHER HEIGHTS
2,Armour Square,13890,393.513552,5860.348806,15.696404,0.024625,ARMOUR SQUARE
3,Ashburn,41098,540.000000,13479.000000,59.468213,0.019123,ASHBURN
4,Auburn Gresham,44878,3364.000000,20617.000000,119.122147,0.049388,AUBURN GRESHAM
...,...,...,...,...,...,...,...
72,West Lawn,33662,525.000000,9701.000000,46.394184,0.024551,WEST LAWN
73,West Pullman,26104,2147.000000,11210.000000,221.071452,0.096914,WEST PULLMAN
74,West Ridge,77122,2185.000000,28054.000000,11.765845,0.005207,WEST RIDGE
75,West Town,87781,3177.000000,41891.000000,62.407906,0.021311,WEST TOWN
76,Woodlawn,24425,2436.000000,11960.000000,122.772101,0.092636,WOODLAWN

In [7]:
df_census[df_census['community_caps']=='THE LOOP']

Empty DataFrame
Columns: [community_name, 2020_pop, vac_hu, hu_tot, vacant, vacperc, community_caps]
Index: []

# Export

In [8]:
df_census.to_csv("../../data/01-tidied/census-by-community.csv", index=False)