# Englewood Exploration
using my best dataset, hopefully to help prepare for interviews and docket requests
2/25/24
I expect 69 dockets (see part I), and now I'm expanding to include info about docket respondent, hearing dates, etc.

In [1]:
import pandas as pd

In [2]:
df_dockets = pd.read_csv("../data/04-standardized/fines-by-docket.csv")
df_dockets

,docket,dept,address,lat,long,community,violation_date,season,n_records,total_fine,binned_fine
0,19DS68300L,STRTSAN,4710 S WESTERN AVE,41.807859,-87.684797,BRIGHTON PARK,2019/11/13,2019-2020,1,150.0,150
1,19DS69216L,STRTSAN,1425 W MORSE AVE,42.007451,-87.666828,ROGERS PARK,2019/11/13,2019-2020,1,50.0,1-149
2,19DS70010L,STRTSAN,715 E 47TH ST,41.809338,-87.608013,GRAND BOULEVARD,2019/11/13,2019-2020,1,150.0,150
3,19DS72153L,STRTSAN,300 W WASHINGTON ST,41.882868,-88.210529,LOOP,2019/11/12,2019-2020,3,650.0,501-8300
4,19DS72160L,STRTSAN,6929 N SHERIDAN RD,41.959813,-87.654693,UPTOWN,2019/11/14,2019-2020,1,500.0,500
...,...,...,...,...,...,...,...,...,...,...,...
1907,23DT000667,TRANPORT,5825 S PULASKI RD,41.786671,-87.722873,WEST ELSDON,2023/01/31,2022-2023,1,150.0,150
1908,23DT000668,TRANPORT,3959 W 58TH ST,41.787691,-87.721975,WEST ELSDON,2023/01/31,2022-2023,1,150.0,150
1909,23DT000669,TRANPORT,4122 W 63RD ST,41.778808,-87.726242,WEST LAWN,2023/02/01,2022-2023,1,500.0,500
1910,23DT000940,TRANPORT,6501 W ARCHER,41.792061,-87.784425,GARFIELD RIDGE,2023/02/01,2022-2023,1,150.0,150
1911,23DT000956,TRANPORT,5601 S NEWCASTLE,41.790217,-87.792223,GARFIELD RIDGE,2023/03/23,2022-2023,2,150.0,150

In [3]:
df_dockets_detailed = pd.read_csv("../data/04-standardized/dockets-detailed.csv")
df_dockets_detailed

,docket,hearing_date,respondent,case_disposition,fine
0,18CP093079,1/24/2019,DOE JOHN,Not Liable,$0.00
1,18DS11011L,4/24/2019,GREATER ST. TITUS MINISTRIES CHURCH OF GOD IN ...,Non-Suit,$0.00
2,18DS16572L,1/7/2019,"CICERO HAMDAN, LLC c/o ILLINOIS SECRETARY OF S...",Liable,$50.00
3,18DS16572L,1/7/2019,"CICERO HAMDAN, LLC c/o MOHAMMED A. NOFAL - ATT...",Liable,$50.00
4,18DS16572L,1/7/2019,HAMDAN SUSAN,Liable,$50.00
...,...,...,...,...,...
4325,24DT000562,5/13/2024,TRIPLE N INVESTMENTS,Pending,$0.00
4326,24DT000563,5/13/2024,YAD CONSTRUCTION,Pending,$0.00
4327,24DT000564,5/13/2024,COLLEEN BECKER,Pending,$0.00
4328,24DT000565,5/13/2024,BURGER KING CO RYAN,Pending,$0.00
4329,24DT000566,5/13/2024,COM ED,Pending,$0.00

# Join and Filter for Englewood Only

In [4]:
df_merge = pd.merge(df_dockets, df_dockets_detailed,on="docket")
df_merge

,docket,dept,address,lat,long,community,violation_date,season,n_records,total_fine,binned_fine,hearing_date,respondent,case_disposition,fine
0,19DS68300L,STRTSAN,4710 S WESTERN AVE,41.807859,-87.684797,BRIGHTON PARK,2019/11/13,2019-2020,1,150.0,150,12/30/2019,"47TH CHGO, LLC c/o ROBERT M. GOMBERG",Liable,$150.00
1,19DS68300L,STRTSAN,4710 S WESTERN AVE,41.807859,-87.684797,BRIGHTON PARK,2019/11/13,2019-2020,1,150.0,150,12/30/2019,"47TH CHGO, LLC c/o SHEFFIELD PROPERTIES L.L.C....",Liable,$150.00
2,19DS69216L,STRTSAN,1425 W MORSE AVE,42.007451,-87.666828,ROGERS PARK,2019/11/13,2019-2020,1,50.0,1-149,1/2/2020,"NOVHAN/MORSE, LLC c/o GEORGE NOVOGRODER",Liable,$50.00
3,19DS70010L,STRTSAN,715 E 47TH ST,41.809338,-87.608013,GRAND BOULEVARD,2019/11/13,2019-2020,1,150.0,150,1/7/2020,DOLLAR TREE STORES INC c/o ILLINOIS CORPORATIO...,Default,$150.00
4,19DS72153L,STRTSAN,300 W WASHINGTON ST,41.882868,-88.210529,LOOP,2019/11/12,2019-2020,3,650.0,501-8300,1/27/2020,"300 W. WASHINGTON, LLC c/o DAVID M. ARNBURG",Continuance,$150.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3651,23DT000668,TRANPORT,3959 W 58TH ST,41.787691,-87.721975,WEST ELSDON,2023/01/31,2022-2023,1,150.0,150,4/3/2023,CBS OUTDOOR,Liable,$150.00
3652,23DT000669,TRANPORT,4122 W 63RD ST,41.778808,-87.726242,WEST LAWN,2023/02/01,2022-2023,1,500.0,500,4/3/2023,"RAZO PROPERTIES LLC, C/O MARTHA RAZO MOLINA",Default,$500.00
3653,23DT000940,TRANPORT,6501 W ARCHER,41.792061,-87.784425,GARFIELD RIDGE,2023/02/01,2022-2023,1,150.0,150,5/8/2023,ESTEBAN LINAREZ,Liable,$150.00
3654,23DT000956,TRANPORT,5601 S NEWCASTLE,41.790217,-87.792223,GARFIELD RIDGE,2023/03/23,2022-2023,2,150.0,150,5/15/2023,"DIESEL CONSTRUCTION BUILDERS INC, C/O JUAN ARR...",Continuance,$150.00
3655,23DT000956,TRANPORT,5601 S NEWCASTLE,41.790217,-87.792223,GARFIELD RIDGE,2023/03/23,2022-2023,2,150.0,150,6/5/2023,"DIESEL CONSTRUCTION BUILDERS INC, C/O JUAN ARR...",Not Liable,$0.00

In [5]:
df_englewood = df_merge[df_merge['community']=='ENGLEWOOD']
df_englewood

,docket,dept,address,lat,long,community,violation_date,season,n_records,total_fine,binned_fine,hearing_date,respondent,case_disposition,fine
721,20DT000786,TRANPORT,6601 S GREEN ST,41.774151,-87.645748,ENGLEWOOD,2020/02/10,2019-2020,1,150.0,150,3/23/2020,VELMA TROTTER,Liable,$150.00
1165,21DS18451M,STRTSAN,6945 S CARPENTER ST,41.767695,-87.650434,ENGLEWOOD,2021/01/02,2020-2021,2,600.0,501-8300,6/18/2021,MATHIS PATRICIA,Default,$0.00
1166,21DS18451M,STRTSAN,6945 S CARPENTER ST,41.767695,-87.650434,ENGLEWOOD,2021/01/02,2020-2021,2,600.0,501-8300,6/18/2021,MATHIS PATRICIA,Default,$600.00
1168,21DS19144M,STRTSAN,7056 S PARNELL AVE,41.765438,-87.638704,ENGLEWOOD,2021/01/27,2020-2021,3,1100.0,501-8300,7/2/2021,AMORANBINI FATAI,Default,$500.00
1169,21DS19144M,STRTSAN,7056 S PARNELL AVE,41.765438,-87.638704,ENGLEWOOD,2021/01/27,2020-2021,3,1100.0,501-8300,7/2/2021,AMORANBINI FATAI,Default,$600.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3524,23DS10124M,STRTSAN,6208 S MAY ST,41.781095,-87.653580,ENGLEWOOD,2022/11/21,2022-2023,3,2300.0,501-8300,5/10/2023,"CHICAGO TITLE LAND TRUST CO., A/T/U/T #8002341...",Default,$600.00
3525,23DS10124M,STRTSAN,6208 S MAY ST,41.781095,-87.653580,ENGLEWOOD,2022/11/21,2022-2023,3,2300.0,501-8300,5/10/2023,"CHICAGO TITLE LAND TRUST CO., A/T/U/T #8002341...",Default,"$1,200.00"
3526,23DS10124M,STRTSAN,6208 S MAY ST,41.781095,-87.653580,ENGLEWOOD,2022/11/21,2022-2023,3,2300.0,501-8300,5/10/2023,STERN MICHAEL,Default,$500.00
3527,23DS10124M,STRTSAN,6208 S MAY ST,41.781095,-87.653580,ENGLEWOOD,2022/11/21,2022-2023,3,2300.0,501-8300,5/10/2023,STERN MICHAEL,Default,$600.00
3528,23DS10124M,STRTSAN,6208 S MAY ST,41.781095,-87.653580,ENGLEWOOD,2022/11/21,2022-2023,3,2300.0,501-8300,5/10/2023,STERN MICHAEL,Default,"$1,200.00"

In [6]:
df_englewood['docket'].nunique()

69

# For Further Analysis

In [7]:
df_englewood.to_csv('../data/04-standardized/dockets-englewood.csv', index=False)