<h1>Snow Violations, 2019-2023</h1>
22 January 2024

START BY READING MY NEW FILE

This analysis looks at 311 complaints filed as "Snow â€“ Uncleared Sidewalk Complaint," or SWSNOREM.<br>
<br>
My analysis steps:
<ol>
<li><a href="#read">Read Data</a>
<li><a href="#ward">By Ward, 1-Year and 5-Year</a>
<li>Ward X
</ol>

<div style="color:red;">
    <h3>Preliminary Findings</h3>
<ul>
    <li>...
</ul>
    </div>

<a name="read"></a>
# 1. Read Data

In [1]:
import pandas as pd
import requests
#import datetime as dt #would only need this if I manipulated dates post-API data retrieval

In [2]:
df = pd.read_csv("../data/311-snow-violations.csv")
df.head()

,SR_NUMBER,SR_SHORT_CODE,CREATED_DATE,STREET_ADDRESS,COMMUNITY_AREA,WARD,STATUS,ORIGIN,CLOSED_DATE,LATITUDE,LONGITUDE,SR_TYPE,year,month,date,season,GEOID,COMMUNITY_NAME
0,SR21-00149474,SDO,2021-01-27 13:13:50,1700 W 15TH ST,28,28,Completed,Mobile Device,2021-01-27 19:50:47,41.861457,-87.668881,Ice and Snow Removal Request,2021,1,2021-01-27,2020-2021,28,Near West Side
1,SR21-00177207,SDO,2021-02-01 10:19:34,1300 S HEATH AVE,28,28,Completed,Mobile Device,2021-02-01 15:12:41,41.864744,-87.684402,Ice and Snow Removal Request,2021,2,2021-02-01,2020-2021,28,Near West Side
2,SR21-00269268,SDO,2021-02-17 12:43:47,819 S BISHOP ST,28,28,Completed,Mobile Device,2021-02-19 00:58:56,41.871081,-87.662624,Ice and Snow Removal Request,2021,2,2021-02-17,2020-2021,28,Near West Side
3,SR21-00149811,SDO,2021-01-27 13:50:04,1300 S WOLCOTT AVE,28,28,Completed,Mobile Device,2021-01-27 19:10:36,41.864893,-87.673790,Ice and Snow Removal Request,2021,1,2021-01-27,2020-2021,28,Near West Side
4,SR21-00188251,SDO,2021-02-02 15:47:03,1200 W LEXINGTON ST,28,28,Completed,Mobile Device,2021-02-02 21:53:42,41.872287,-87.656946,Ice and Snow Removal Request,2021,2,2021-02-02,2020-2021,28,Near West Side

In [3]:
len(df)

68273

### look at just full years

In [4]:
df = df[(df['season'].isin(['2019-2020','2020-2021','2021-2022','2022-2023']))]
len(df)

67361

<a name="ward"></a>
# 2. By Ward, 2019-2023

In [9]:
df.groupby('WARD').size()

WARD
1     2138
2     1184
3     1125
4     1076
5      968
6     1248
7     1001
8     1625
9     1390
10     951
11    1384
12    1080
13    1061
14    1713
15    1094
16    1242
17    1481
18    2086
19     776
20    1306
21    2024
22     973
23    1224
24    1213
25    1730
26    1553
27    2101
28    1420
29    1130
30    1606
31    1171
32    2371
33    1584
34    1860
35    1119
36    1080
37    1453
38     976
39    1464
40    1599
41    1010
42     750
43    1298
44    1369
45    1481
46    1014
47    2156
48     815
49     717
50    1171
dtype: int64

In [20]:
df_ward_by_season= df.pivot_table(index='WARD',columns='season',values='SR_NUMBER',aggfunc='count').reset_index()
df_ward_by_season

season  WARD  2019-2020  2020-2021  2021-2022  2022-2023
0          1        468        938        621        111
1          2        278        461        353         92
2          3        160        556        342         67
3          4        132        552        331         61
4          5         88        448        308        124
5          6         88        665        382        113
6          7         90        575        277         59
7          8        127        850        495        153
8          9        154        761        421         54
9         10        100        291        513         47
10        11        176        592        548         68
11        12        110        470        444         56
12        13        102        435        408        116
13        14        122        709        754        128
14        15         94        483        441         76
15        16         90        567        510         75
16        17        111        729        525        116
17        18        141       1048        795        102
18        19         97        345        310         24
19        20        115        655        437         99
20        21         98       1137        711         78
21        22         88        403        426         56
22        23        132        494        533         65
23        24         92        713        346         62
24        25        280        736        658         56
25        26        248        664        566         75
26        27        284       1133        612         72
27        28        171        800        396         53
28        29        107        621        342         60
29        30        221        708        565        112
30        31        110        549        414         98
31        32        637        925        635        174
32        33        255        683        548         98
33        34        102        991        731         36
34        35        191        503        371         54
35        36        127        462        450         41
36        37        102        701        525        125
37        38        193        477        232         74
38        39        363        635        402         64
39        40        299        723        478         99
40        41        270        412        231         97
41        42        219        277        203         51
42        43        441        472        319         66
43        44        482        512        281         94
44        45        224        773        398         86
45        46        227        342        305        140
46        47        506        900        609        141
47        48        245        240        254         76
48        49        213        231        190         83
49        50        322        467        362         20

In [22]:
df_ward_by_season.to_csv("../results/ward_by_season.csv", index=False)