# Matching Streets & Sans Sidewalk Snow Clearance Fines to Building Violations in Englewood
2/15/24 RR

This notebook attempts to join court dockets for snow clearance fines, to three other recordsets:
<ol>
    <li>bank-owned vacant property violations
    <li>vacant property complaints
    </ol>

### overview of datasets
<div style="color:red">describe each data set here</div>

### next steps
<div style="color:red">
    roll up 311 complaints (snow and building violations) by address
    </div>

# 1. Read and Review all Datasets

In [52]:
import pandas as pd

In [53]:
df_addresses = pd.read_csv("../results/fines_by_address.csv")
df_dockets = pd.read_csv("../results/fines_by_docket.csv")
# df_311_snow = pd.read_csv("../data/311-complaints-snow.csv")
df_311_vacant = pd.read_csv("../data/311-complaints-vacant.csv")
#df_vacant_violations = pd.read_csv("../data/vacant-violations.csv")

/tmp/ipykernel_986/2030219279.py:4: DtypeWarning: Columns (20,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df_311_vacant = pd.read_csv("../data/311-complaints-vacant.csv")

### filter by Englewood

In [54]:
df_englewood = df_dockets[(df_dockets['community']=='ENGLEWOOD')]

### fines by department

In [55]:
df_englewood.groupby("dept").size().reset_index(name="n")

       dept   n
0    POLICE   4
1   STRTSAN  58
2  TRANPORT   7

### filter by streets and sanitation

In [56]:
df_englewood_ss = df_englewood[(df_englewood['dept']=='STRTSAN')]

In [57]:
len(df_englewood_ss)

58

In [59]:
df_englewood_ss.head()

,docket,dept,address,lat,long,community,violation_date,season,n_records,total_fine,binned_fine
362,21DS18451M,STRTSAN,6945 S CARPENTER ST,41.767695,-87.650434,ENGLEWOOD,2021/01/02,2020-2021,2,600.0,501-8300
364,21DS19144M,STRTSAN,7056 S PARNELL AVE,41.765438,-87.638704,ENGLEWOOD,2021/01/27,2020-2021,3,1100.0,501-8300
442,21DS20741M,STRTSAN,932 W 59TH ST,41.787053,-87.648811,ENGLEWOOD,2021/02/13,2020-2021,3,600.0,501-8300
451,21DS20811M,STRTSAN,6701 S RACINE AVE,41.772152,-87.654042,ENGLEWOOD,2021/02/20,2020-2021,2,400.0,151-499
454,21DS47172M,STRTSAN,6215 S MORGAN ST,41.780971,-87.649399,ENGLEWOOD,2021/10/08,2021-2022,1,100.0,1-149

### 311 vacant property complaints

In [60]:
df_311_vacant.head()

,SR_NUMBER,SR_TYPE,SR_SHORT_CODE,CREATED_DEPARTMENT,OWNER_DEPARTMENT,STATUS,ORIGIN,CREATED_DATE,LAST_MODIFIED_DATE,CLOSED_DATE,...,Y_COORDINATE,LATITUDE,LONGITUDE,LOCATION,Boundaries - ZIP Codes,Community Areas,Zip Codes,Census Tracts,Wards,Boundaries - Wards (2023-)
0,SR24-00281470,Vacant/Abandoned Building Complaint,BBK,Alderman,DOB - Buildings,Open,Alderman's Office,02/14/2024 03:06:53 PM,02/14/2024 03:06:57 PM,NaN,...,1.923340e+06,41.946093,-87.833084,"(41.946093000940635, -87.83308350000193)",52.0,17.0,22254.0,445.0,19.0,38.0
1,SR24-00281118,Clean Vacant Lot Request,SCT,NaN,Streets and Sanitation,Open,Internet,02/14/2024 02:37:49 PM,02/14/2024 03:00:32 PM,NaN,...,1.900875e+06,41.883990,-87.737984,"(41.88398957298473, -87.73798373959555)",30.0,27.0,21572.0,732.0,23.0,28.0
2,SR24-00281087,Clean Vacant Lot Request,SCT,NaN,Streets and Sanitation,Open,Internet,02/14/2024 02:34:45 PM,02/14/2024 03:00:32 PM,NaN,...,1.900875e+06,41.883990,-87.737984,"(41.88398957298473, -87.73798373959555)",30.0,27.0,21572.0,732.0,23.0,28.0
3,SR24-00281058,Clean Vacant Lot Request,SCT,NaN,Streets and Sanitation,Open,Mobile Device,02/14/2024 02:31:25 PM,02/14/2024 02:31:27 PM,NaN,...,1.868779e+06,41.795712,-87.701359,"(41.79571200094013, -87.70135950000191)",56.0,61.0,22248.0,777.0,8.0,14.0
4,SR24-00280702,Vacant/Abandoned Building Complaint,BBK,Alderman,DOB - Buildings,Open,Alderman's Office,02/14/2024 01:58:26 PM,02/14/2024 01:58:29 PM,NaN,...,1.852913e+06,41.751891,-87.652319,"(41.751891000939985, -87.6523185000019)",59.0,70.0,21554.0,487.0,31.0,17.0

# 2. Match Dockets to 311 complaints about vacants

In [61]:
df_match_englewood = pd.merge(df_englewood_ss,df_311_vacant,left_on="address",right_on="STREET_ADDRESS", how="left")
df_match_englewood

,docket,dept,address,lat,long,community,violation_date,season,n_records,total_fine,...,Y_COORDINATE,LATITUDE,LONGITUDE,LOCATION,Boundaries - ZIP Codes,Community Areas,Zip Codes,Census Tracts,Wards,Boundaries - Wards (2023-)
0,21DS18451M,STRTSAN,6945 S CARPENTER ST,41.767695,-87.650434,ENGLEWOOD,2021/01/02,2020-2021,2,600.0,...,1.858588e+06,41.767453,-87.650268,"(41.7674533653731, -87.65026834788003)",11.0,66.0,21559.0,410.0,32.0,16.0
1,21DS19144M,STRTSAN,7056 S PARNELL AVE,41.765438,-87.638704,ENGLEWOOD,2021/01/27,2020-2021,3,1100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21DS20741M,STRTSAN,932 W 59TH ST,41.787053,-87.648811,ENGLEWOOD,2021/02/13,2020-2021,3,600.0,...,1.865735e+06,41.787059,-87.648701,"(41.78705884320334, -87.64870084226511)",11.0,66.0,21559.0,113.0,2.0,16.0
3,21DS20811M,STRTSAN,6701 S RACINE AVE,41.772152,-87.654042,ENGLEWOOD,2021/02/20,2020-2021,2,400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,21DS47172M,STRTSAN,6215 S MORGAN ST,41.780971,-87.649399,ENGLEWOOD,2021/10/08,2021-2022,1,100.0,...,1.863518e+06,41.780978,-87.649406,"(41.78097839180529, -87.64940555132205)",11.0,66.0,21559.0,22.0,2.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,22DS04357M,STRTSAN,6448 S ABERDEEN ST,41.776391,-87.652268,ENGLEWOOD,2022/02/11,2021-2022,3,1100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,22DS04371M,STRTSAN,6441 S ABERDEEN ST,41.776569,-87.651701,ENGLEWOOD,2022/02/11,2021-2022,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,22DS04377M,STRTSAN,6459 S ABERDEEN ST,41.776129,-87.651701,ENGLEWOOD,2022/02/11,2021-2022,1,500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,22DS04683M,STRTSAN,5936 S UNION AVE,41.786051,-87.642621,ENGLEWOOD,2022/02/18,2021-2022,5,1550.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,23DS10124M,STRTSAN,6208 S MAY ST,41.781095,-87.653580,ENGLEWOOD,2022/11/21,2022-2023,3,2300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
df_match_englewood.to_csv("../results/englewood/fines_streets_englewood.csv", index=False)